### PR TITLE
fix: Eliminate global variable

### LINKED ISSUE #62: Eliminate global variables inside project
Global variables and global pointers have existed for a long time inside project, such as connectivity/conn_http.h, for good coding style. We should eliminate them.

_Originally posted by @jserv in https://github.com/DLTcollab/TA-endpoint/pull/57/files_

### PR DESCRIPTION
**Pull request by splasky**
The `http_res_body` is a global pointer for printing debug
message inside send_http_msg. The pointer can be reduced and print the
debug message inside callback function.

closes #62

### CODE REVIEW

File: connectivity/conn_http.c [hunk 1]
```diff
@@ -231,6 +231,8 @@ retcode_t set_get_request(char const *const path, char const *const host, const
 }
 
 int parser_body_callback(http_parser *parser, const char *at, size_t length) {
-  http_res_body = strdup(at);
+#ifdef DEBUG
+  printf("HTTP Response: %s\n", at);
```
Comment (jserv) [inline connectivity/conn_http.c:235]: Is it equivalent for dumping debug message?

Comment (splasky) [reply connectivity/conn_http.c:235]: Yes. But the `http_res_body` will not use anymore.
