### PR TITLE
fix: Add post request body

### LINKED ISSUE #68: Request body is missing
Request body is missing when POST request sending to tangle-accelerator.

### PR DESCRIPTION
**Pull request by splasky**
Fix missing post request body when sending message to tangle-accelerator.
closes #68

### CODE REVIEW

File: main.c [hunk 1]
```diff
@@ -19,7 +19,7 @@
 #include "utils/trytes.h"
 #include "utils/uart_utils.h"
 
-#define HOST "tangle-accel.puyuma.org"
+#define HOST "tangle-accel.biilabs.io"
```
Comment (jserv) [inline main.c]: Don't change host in this pull request. Concentrate on your subject.

File: main.c [hunk 2]
```diff
@@ -145,8 +145,11 @@ int main(int argc, char *argv[]) {
       serialize_msg(iv, ciphertext_len, ciphertext, msg, &msg_len);
       bytes_to_trytes((const unsigned char *)msg, msg_len, tryte_msg);
 
+      char msg_body[1024];
```
Comment (howjmay) [inline main.c]: How about declare the size of string with macro?

**Review by howjmay — CHANGES_REQUESTED** [review]
